### ISSUE TITLE
Pod "not compatible with DuoAPISwift" error

### ISSUE THREAD

**Issue by archer29m** [duosecurity/duo_api_swift#9]
Hello,

I tried to setup the API through pod. 
But I get the following error:
`The platform of the target MyProject (iOS 13.0) is not compatible with DuoAPISwift (2.1.0), which does not support iOS.` 
I have defined different target versions (both in pod and Xcode deployment) but no success. 
Any idea?

Thanks.

**Comment by BilalPervez** [comment]
@archer29m did you get any solution for this error? I'm facing same error on my side.

**Comment by AaronAtDuo** [comment]
Closing out old tickets
